# Generated by Django 3.1.7 on 2021-03-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210304_1458"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="epicmember",
            managers=[],
        ),
    ]
