# Generated by Django 3.1.7 on 2021-03-05 14:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210305_1414"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="epicmember",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
