# Generated by Django 3.1.7 on 2021-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210305_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epicmember",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="epicmember",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Last name"
            ),
        ),
    ]
