# Generated by Django 3.1.7 on 2021-03-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20210310_1530"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="epicmember",
            managers=[],
        ),
    ]
