# Generated by Django 3.1.7 on 2021-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20210310_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epicmember",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
