# Generated by Django 3.1.7 on 2021-03-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compagny_name",
                    models.CharField(max_length=250, verbose_name="Company name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROSPECT", "Potential Client"),
                            ("SIGNED", "Current Client"),
                            ("OLD", "Lost Client"),
                        ],
                        default="PROSPECT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(max_length=25, verbose_name="Contact first name"),
                ),
                (
                    "contact_last_name",
                    models.CharField(max_length=25, verbose_name="Contact last name"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=100, verbose_name="Contact email"),
                ),
                (
                    "contact_mobile",
                    models.CharField(max_length=20, verbose_name="Contact mobile"),
                ),
                (
                    "company_phone",
                    models.CharField(max_length=20, verbose_name="Company phone"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPENED", "Waiting for a signature"),
                            ("SIGNED", "Signed"),
                            ("PAID", "Paid"),
                        ],
                        default="OPENED",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("amount", models.FloatField()),
                ("payment_date", models.DateTimeField(verbose_name="Payment date")),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPENED", "Need a support contact"),
                            ("PLAN", "To planify"),
                            ("PREPARE", "To prepare"),
                            ("PRODUCE", "To produce"),
                            ("PERFECT", "To perfect"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPENED",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("attendess", models.PositiveIntegerField()),
                ("notes", models.TextField(max_length=8192, verbose_name="Notes")),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Event starting date"),
                ),
                ("close_date", models.DateTimeField(verbose_name="Event ending date")),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_events",
                        to="crm.contract",
                    ),
                ),
            ],
        ),
    ]
