# Generated by Django 3.1.7 on 2021-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210304_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('PROSPECT', 'Potential Client'), ('SIGNED', 'Current Client'), ('OLD', 'Lost Client')], default='PROSPECT', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
