# Generated by Django 3.1.7 on 2021-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_auto_20210304_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment date"),
        ),
    ]
