# Generated by Django 3.1.7 on 2021-03-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_auto_20210304_1555"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="compagny_name",
            new_name="company_name",
        ),
    ]
