# Generated by Django 3.1.7 on 2021-03-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_auto_20210304_1639"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="attendess",
            new_name="attendees",
        ),
    ]
