# Generated by Django 3.1.7 on 2021-03-11 11:36

from django.db import migrations


def load_status(apps, schema_editor):
    Status = apps.get_model("crm", "Status")

    # CLIENT INITIAL STATUS
    client_prospect = Status(table="CLIENT", value="PROSPECT", label="Potential Client")
    client_prospect.save()

    client_signed = Status(table="CLIENT", value="SIGNED", label="Current Client")
    client_signed.save()

    client_old = Status(table="CLIENT", value="OLD", label="Lost Client")
    client_old.save()

    # CONTRACT INITIAL STATUS
    contract_new = Status(table="CONTRACT", value="OPENED", label="Waiting for a signature")
    contract_new.save()

    contract_signed = Status(table="CONTRACT", value="SIGNED", label="Signed")
    contract_signed.save()

    contract_new = Status(table="CONTRACT", value="PAID", label="Paid")
    contract_new.save()

    # EVENT INITIAL STATUS
    event_new = Status(table="EVENT", value="OPENED", label="Need a support contact")
    event_new.save()

    event_plan = Status(table="EVENT", value="PLAN", label="To planify")
    event_plan.save()

    event_closed = Status(table="EVENT", value="CLOSED", label="Closed")
    event_closed.save()


def delete_status(apps, schema_editor):
    Status = apps.get_model("crm", "Status")
    Status.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_status'),
    ]

    operations = [
        migrations.RunPython(load_status, delete_status),
    ]
