# Generated by Django 3.1.7 on 2021-03-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_auto_20210311_1136"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="status",
            unique_together={("table", "value")},
        ),
    ]
