# Generated by Django 3.1.7 on 2021-03-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20210311_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.ForeignKey(limit_choices_to={'table': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, to='crm.status'),
        ),
    ]
