# Generated by Django 3.1.7 on 2021-03-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_auto_20210311_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"table": "CONTRACT"},
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.status",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"table": "EVENT"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_events",
                to="crm.status",
            ),
        ),
    ]
