# Generated by Django 3.1.7 on 2021-03-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20210311_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'table': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'table': 'CONTRACT'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'table': 'EVENT'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='crm.status'),
        ),
    ]
